spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27016
      database: chat_app
      authentication-database: admin

  logging:
    level:
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG
      org.springframework.messaging.simp: DEBUG
      org.springframework.messaging.simp.stomp: TRACE

server:
  port: 8088